# 04.07 - Python + NumPy for CV

**Notebook type:** Practice notebook with theory, exercises, and TODO cells.

**Daily output:** shape manipulation notebook.

Today is about array confidence: shapes, indexing, channel order, dtype, normalization, and reproducibility. These are the foundations under image loading, transforms, CNNs, and DataLoaders.


## CV Array Conventions

Common image shapes:

- grayscale image: `[H, W]`
- color image in NumPy/PIL/OpenCV: `[H, W, C]`
- PyTorch image tensor: `[C, H, W]`
- batch of PyTorch images: `[B, C, H, W]`

Common dtypes:

- raw image from disk: `uint8`, usually range `0..255`
- model input: `float32`, usually range `0..1`, then optionally normalized


In [1]:
import random
import numpy as np

SEED = 42
random.seed(SEED)
np.random.seed(SEED)


## Exercise 04-A: dtype and Normalization

Convert `[0, 127, 255]` from `uint8` to float values in `[0, 1]`.


In [4]:
# TODO 04-A
# Create u8 = np.array([0, 127, 255], dtype=np.uint8)
# Convert to float32 in range [0, 1].
# Print output and dtype.

u8 = np.array([0,127,255], dtype = np.uint8)
u8 = u8 / 255.0
u8 = u8.astype(np.float32)
print(u8)
print(u8.dtype)

[0.         0.49803922 1.        ]
float32


## Exercise 04-B: HWC to CHW

PyTorch expects channel-first images. Convert an image from `[H, W, C]` to `[C, H, W]`.


In [5]:
# TODO 04-B
# Create image = np.arange(2 * 3 * 3).reshape(2, 3, 3)
# Convert HWC -> CHW using np.transpose.
# Print original shape, converted shape, and the first channel.

image = np.arange(2 * 3 * 3).reshape(2,3,3)
print(image.shape)
image = np.transpose(image, (2,0,1))
print(image.shape)
print(image[0])

(2, 3, 3)
(3, 2, 3)
[[ 0  3  6]
 [ 9 12 15]]


## Exercise 04-C: Batch Construction

A batch of two RGB images for PyTorch should be `[B, C, H, W]`.


In [8]:
# TODO 04-C
# Create two images with shape [4, 5, 3].
# Convert each to CHW, stack into a batch, and print shape.

img1 = np.arange(4*5*3).reshape(4,5,3)
img2 = np.zeros((4,5,3))
img1 = np.transpose(img1, (2,0,1))
img2 = np.transpose(img2, (2,0,1))
batch = np.array([img1,img2])
print(batch.shape)


(2, 3, 4, 5)


## Exercise 04-D: Mean/Std Normalization

ImageNet-style normalization subtracts a per-channel mean and divides by a per-channel std. Broadcasting is your friend here.


In [13]:
# TODO 04-D
# img shape: [2, 2, 3], all ones, dtype float32
# mean: [0.5, 1.0, 1.5]
# std: [0.5, 0.5, 0.5]
# Compute normalized image and print shape.
img = np.ones((2,2,3))
mean = [0.5,1.0,1.5]
std = [0.5,0.5,0.5]
img = (img-mean)/std
print(img)


[[[ 1.  0. -1.]
  [ 1.  0. -1.]]

 [[ 1.  0. -1.]
  [ 1.  0. -1.]]]


## Exercise 04-E: Channel Order

Simulate one RGB pixel and convert it to BGR. This is the tiny version of the PIL/OpenCV mismatch.


In [14]:
# TODO 04-E
rgb_pixel = np.array([[[255, 0, 0]]], dtype=np.uint8)
# Convert RGB -> BGR by reversing the last axis.
# Print both pixels.
bgr_pixel = rgb_pixel[:,:,::-1]
print(bgr_pixel)

[[[  0   0 255]]]
